//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLVLXD
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHTOAN
    {
        public string SOPHIEU { get; set; }
        public Nullable<System.DateTime> NGAYPHIEU { get; set; }
        public Nullable<int> SOTIEN { get; set; }
        public string MAKHACH { get; set; }
    
        public virtual KHACH KHACH { get; set; }
    }
}
